In [2]:
import pandas as pd

**A. Load the penguins dataset into a Pandas dataframe.**

In [3]:
df = pd.read_csv('penguins.csv')

In [4]:
df

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

**B. Determine the number of observations/records and the number of attributes in the dataframe.**

In [6]:
df.describe()

,rowid,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,344.000000,342.000000,342.000000,342.000000,342.000000,344.000000
mean,172.500000,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,99.448479,5.459584,1.974793,14.061714,801.954536,0.818356
min,1.000000,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,86.750000,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,172.500000,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,258.250000,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,344.000000,59.600000,21.500000,231.000000,6300.000000,2009.000000

**C. Display the names of the attributes, row indexes, and data types of each attribute in the dataframe.**

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    int64
 1   species            344 non-null    object
 2   island             344 non-null    object
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object
 8   year               344 non-null    int64
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB

In [18]:
df.columns

Index(['rowid', 'species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='object')

**D. Display the first 5 and last 5 records of the dataframe.**

In [15]:
df.head()

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [17]:
df.tail()

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

**E. Retrieve the values of the second column for the third and fourth records.**

In [23]:
df.iloc[[2,3],1]

2    Adelie
3    Adelie
Name: species, dtype: object

**F. Display a summary of the data distribution for all attributes in the dataframe.**

In [29]:
df.cov(numeric_only = True)

,rowid,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
rowid,9890.000000,414.774595,-50.835427,635.047950,21911.008643,27.597668
bill_length_mm,414.774595,29.807054,-2.534234,50.375765,2605.591912,0.243345
bill_depth_mm,-50.835427,-2.534234,3.899808,-16.212950,-747.370093,-0.097395
flipper_length_mm,635.047950,50.375765,-16.212950,197.731792,9824.416062,1.949701
body_mass_g,21911.008643,2605.591912,-747.370093,9824.416062,643131.077327,27.661162
year,27.597668,0.243345,-0.097395,1.949701,27.661162,0.669706

**G. Compute the pairwise correlation between all attributes in the dataframe.**

In [52]:
df.corr(numeric_only = True)

,rowid,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
rowid,1.000000,0.766039,-0.259563,0.455372,0.275493,0.339103
bill_length_mm,0.766039,1.000000,-0.235053,0.656181,0.595110,0.054545
bill_depth_mm,-0.259563,-0.235053,1.000000,-0.583851,-0.471916,-0.060354
flipper_length_mm,0.455372,0.656181,-0.583851,1.000000,0.871202,0.169675
body_mass_g,0.275493,0.595110,-0.471916,0.871202,1.000000,0.042209
year,0.339103,0.054545,-0.060354,0.169675,0.042209,1.000000

**H. Identify the most correlated positively correlated attributes and negatively correlated
attributes**

In [31]:
df.corr(numeric_only = True)

,rowid,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
rowid,1.000000,0.766039,-0.259563,0.455372,0.275493,0.339103
bill_length_mm,0.766039,1.000000,-0.235053,0.656181,0.595110,0.054545
bill_depth_mm,-0.259563,-0.235053,1.000000,-0.583851,-0.471916,-0.060354
flipper_length_mm,0.455372,0.656181,-0.583851,1.000000,0.871202,0.169675
body_mass_g,0.275493,0.595110,-0.471916,0.871202,1.000000,0.042209
year,0.339103,0.054545,-0.060354,0.169675,0.042209,1.000000

**I. Find covariance between att1 and att2**

In [32]:
df['rowid'].corr(df['bill_length_mm'])

0.766038569429124

**J. Print the unique values of species column**

In [33]:
df['species'].unique()

array(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)

**K. Find the  min and Max values of  body_mass_g**

In [38]:
df['body_mass_g'].max()

6300.0

**Find count of penguins with bill_length_mm less than 35**

In [51]:
df[df['bill_length_mm']<35]['bill_length_mm'].count()

9

In [45]:
df2.value_counts()

bill_length_mm
False    335
True       9
Name: count, dtype: int64

**Find total count of male and female penguins**

In [47]:
df['sex'].value_counts()

sex
male      168
female    165
Name: count, dtype: int64