In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'staff':['A','B','C','D','E','F'],
                    'issues':[18,22,29,25,14,11],
                    'assists':[4,5,5,4,8,12],
                    'rebounds':[10,6,4,6,3,5]})

In [3]:
print(df1)

  staff  issues  assists  rebounds
0     A      18        4        10
1     B      22        5         6
2     C      29        5         4
3     D      25        4         6
4     E      14        8         3
5     F      11       12         5

In [4]:
df2 = pd.DataFrame({'staff':['A','B','C','D','E','F'],
                    'issues':[22,25,27,35,25,20],
                    'assists':[15,13,8,8,5,8],
                    'rebs':[4,11,12,8,7,10]})

In [5]:
print(df2)

  staff  issues  assists  rebs
0     A      22       15     4
1     B      25       13    11
2     C      27        8    12
3     D      35        8     8
4     E      25        5     7
5     F      20        8    10

In [7]:
df = {
    "Array_":[30,70,100],
    "Array_2":[65.1,49.50,30.7]
}

In [8]:
data = pd.DataFrame(df)

In [9]:
print(data.corr())

           Array_   Array_2
Array_   1.000000 -0.990773
Array_2 -0.990773  1.000000

In [37]:
df1.corrwith(df2,numeric_only=True)

issues      0.677051
assists    -0.478184
rebounds         NaN
rebs             NaN
dtype: float64

In [24]:
df3 = pd.DataFrame({'issues':[18,22,29,25,14,11],
                    'assists':[4,5,5,4,8,12],
                    'rebounds':[10,6,4,6,3,5]})

In [20]:
df4 = pd.DataFrame({'issues':[22,25,27,35,25,20],
                    'assists':[15,13,8,8,5,8],
                    'rebs':[4,11,12,8,7,10]})

In [21]:
df3.corrwith(df4)

issues      0.677051
assists    -0.478184
rebounds         NaN
rebs             NaN
dtype: float64

**Class Work**

In [25]:
df1.tail(3)

  staff  issues  assists  rebounds
3     D      25        4         6
4     E      14        8         3
5     F      11       12         5

In [26]:
df1['issues'].corr(df2['rebs'])

0.38661297414864526

In [29]:
df3.corr()

            issues  assists  rebounds
issues    1.000000 -0.77466  0.008102
assists  -0.774660  1.00000 -0.455650
rebounds  0.008102 -0.45565  1.000000

In [30]:
df3.cov()

             issues    assists  rebounds
issues    46.166667 -16.533333  0.133333
assists  -16.533333   9.866667 -3.466667
rebounds   0.133333  -3.466667  5.866667

In [31]:
df3

   issues  assists  rebounds
0      18        4        10
1      22        5         6
2      29        5         4
3      25        4         6
4      14        8         3
5      11       12         5

In [32]:
df1

  staff  issues  assists  rebounds
0     A      18        4        10
1     B      22        5         6
2     C      29        5         4
3     D      25        4         6
4     E      14        8         3
5     F      11       12         5

In [36]:
df1.corr(numeric_only=True)

            issues  assists  rebounds
issues    1.000000 -0.77466  0.008102
assists  -0.774660  1.00000 -0.455650
rebounds  0.008102 -0.45565  1.000000

In [35]:
df1.describe()

          issues    assists   rebounds
count   6.000000   6.000000   6.000000
mean   19.833333   6.333333   5.666667
std     6.794606   3.141125   2.422120
min    11.000000   4.000000   3.000000
25%    15.000000   4.250000   4.250000
50%    20.000000   5.000000   5.500000
75%    24.250000   7.250000   6.000000
max    29.000000  12.000000  10.000000